# Generated by Django 3.0.5 on 2020-09-18 12:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('route_title', models.CharField(max_length=40)),
                ('route_author', models.CharField(max_length=30)),
                ('route_rank', models.IntegerField()),
                ('route_type', models.BooleanField(default=True)),
                ('region', models.CharField(max_length=30)),
                ('placemant_and_belay_anchor', models.IntegerField()),
                ('route_description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
