# Generated by Django 3.0.5 on 2020-09-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoCrudApp', '0002_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Pages',
        ),
    ]
