# Generated by Django 3.0.5 on 2020-09-27 19:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoCrudApp', '0003_auto_20200925_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=50)),
                ('group_of_regions', models.CharField(max_length=50)),
            ],
        ),
    ]
