# Generated by Django 3.0.5 on 2020-10-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoCrudApp', '0007_auto_20201012_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='region',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
